[package]
name = "face-value"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = "0.4"
dioxus-web = "0.4"
chrono = "0.4"
log = "0.4"
wasm-logger = "0.2"
web-sys = { version = "0.3", features = ["Window", "Location"] }
