[package]
name = "face-value"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
dioxus = "0.4"
dioxus-web = "0.4"
chrono = "0.4"
log = "0.4"
wasm-logger = "0.2"
web-sys = { version = "0.3", features = ["Window", "Location"] }
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1.7"

# Enable better optimizations for WASM
[profile.release]
opt-level = 2
lto = true
codegen-units = 1
