[build]
# The index HTML file to drive the bundling process.
target = "index.html"
# Build in release mode.
release = true
# The output dir for all final assets.
dist = "dist"
# The public URL from which assets are to be served.
public_url = "/face-value/"
# Enable asset inlining for release builds
inline = true

[[hooks]]
stage = "pre_build"
command = "sh"
command_arguments = ["-c", "mkdir -p dist"]

[watch]
watch = ["src", "index.html"]

# Configure serving
[serve]
port = 8080
